version: '3.8'

services:
  db:
    image: postgres:15
    container_name: paymentapi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build: .
    container_name: paymentapi-api
    environment:
      # Строка подключения внутри Docker использует имя контейнера db
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=paymentapi;Username=postgres;Password=postgres
      - Jwt__Key=SuperSecretKey123456
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"

volumes:
  db_data:


